name: grow
description: "App by Discipline"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.20
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.0
  image_picker: ^1.1.0
  shared_preferences: ^2.1.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.2.1
  google_fonts: ^6.2.1
  rxdart: ^0.27.0
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_image_compress: ^2.0.0
  path_provider: ^2.1.0
  path: ^1.8.3
  youtube_player_iframe: ^4.0.4
  permission_handler: ^11.0.0
  fl_chart: ^0.66.0
  timeago: ^3.4.0
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^9.0.0
  flutter_markdown: ^0.6.18
  video_player: ^2.7.2
  chewie: ^1.7.1
  youtube_explode_dart: ^2.0.2
  package_info_plus: ^4.0.0
  share_plus: ^7.2.1
  uuid: ^4.2.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  audio_waveforms: ^1.0.4
  audioplayers: ^5.2.1
  flutter_local_notifications: ^16.3.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icono_app.jpg"
  image_path_android: "assets/icono_app.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icono_app.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/grow_baja_calidad_negro.png
    - assets/grow_baja_calidad_blanco.png
    - assets/default_avatar.png